/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppModerationRouteImport } from './routes/_app/moderation'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConciergeRouteImport } from './routes/_app/concierge'
import { Route as AppStudyNookIndexRouteImport } from './routes/_app/study-nook/index'
import { Route as AppLobbyIndexRouteImport } from './routes/_app/lobby/index'
import { Route as AppGuideIndexRouteImport } from './routes/_app/guide/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppStudyNookZoneIdRouteImport } from './routes/_app/study-nook/$zoneId'
import { Route as AppLobbyThreadIdRouteImport } from './routes/_app/lobby/$threadId'
import { Route as AppGuideEstIdRouteImport } from './routes/_app/guide/$estId'
import { Route as AppAdminLogsRouteImport } from './routes/_app/admin/logs'
import { Route as AppAdminEstablishmentsRouteImport } from './routes/_app/admin/establishments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConciergeRoute = AppConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudyNookIndexRoute = AppStudyNookIndexRouteImport.update({
  id: '/study-nook/',
  path: '/study-nook/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLobbyIndexRoute = AppLobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGuideIndexRoute = AppGuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudyNookZoneIdRoute = AppStudyNookZoneIdRouteImport.update({
  id: '/study-nook/$zoneId',
  path: '/study-nook/$zoneId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLobbyThreadIdRoute = AppLobbyThreadIdRouteImport.update({
  id: '/lobby/$threadId',
  path: '/lobby/$threadId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGuideEstIdRoute = AppGuideEstIdRouteImport.update({
  id: '/guide/$estId',
  path: '/guide/$estId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminEstablishmentsRoute = AppAdminEstablishmentsRouteImport.update({
  id: '/admin/establishments',
  path: '/admin/establishments',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/concierge': typeof AppConciergeRoute
  '/dashboard': typeof AppDashboardRoute
  '/moderation': typeof AppModerationRoute
  '/profile': typeof AppProfileRoute
  '/admin/establishments': typeof AppAdminEstablishmentsRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/guide/$estId': typeof AppGuideEstIdRoute
  '/lobby/$threadId': typeof AppLobbyThreadIdRoute
  '/study-nook/$zoneId': typeof AppStudyNookZoneIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/guide/': typeof AppGuideIndexRoute
  '/lobby/': typeof AppLobbyIndexRoute
  '/study-nook/': typeof AppStudyNookIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/concierge': typeof AppConciergeRoute
  '/dashboard': typeof AppDashboardRoute
  '/moderation': typeof AppModerationRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/admin/establishments': typeof AppAdminEstablishmentsRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/guide/$estId': typeof AppGuideEstIdRoute
  '/lobby/$threadId': typeof AppLobbyThreadIdRoute
  '/study-nook/$zoneId': typeof AppStudyNookZoneIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/guide': typeof AppGuideIndexRoute
  '/lobby': typeof AppLobbyIndexRoute
  '/study-nook': typeof AppStudyNookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/concierge': typeof AppConciergeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/moderation': typeof AppModerationRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/establishments': typeof AppAdminEstablishmentsRoute
  '/_app/admin/logs': typeof AppAdminLogsRoute
  '/_app/guide/$estId': typeof AppGuideEstIdRoute
  '/_app/lobby/$threadId': typeof AppLobbyThreadIdRoute
  '/_app/study-nook/$zoneId': typeof AppStudyNookZoneIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/guide/': typeof AppGuideIndexRoute
  '/_app/lobby/': typeof AppLobbyIndexRoute
  '/_app/study-nook/': typeof AppStudyNookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/concierge'
    | '/dashboard'
    | '/moderation'
    | '/profile'
    | '/admin/establishments'
    | '/admin/logs'
    | '/guide/$estId'
    | '/lobby/$threadId'
    | '/study-nook/$zoneId'
    | '/admin/'
    | '/guide/'
    | '/lobby/'
    | '/study-nook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/concierge'
    | '/dashboard'
    | '/moderation'
    | '/profile'
    | '/'
    | '/admin/establishments'
    | '/admin/logs'
    | '/guide/$estId'
    | '/lobby/$threadId'
    | '/study-nook/$zoneId'
    | '/admin'
    | '/guide'
    | '/lobby'
    | '/study-nook'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/concierge'
    | '/_app/dashboard'
    | '/_app/moderation'
    | '/_app/profile'
    | '/_app/'
    | '/_app/admin/establishments'
    | '/_app/admin/logs'
    | '/_app/guide/$estId'
    | '/_app/lobby/$threadId'
    | '/_app/study-nook/$zoneId'
    | '/_app/admin/'
    | '/_app/guide/'
    | '/_app/lobby/'
    | '/_app/study-nook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/concierge': {
      id: '/_app/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AppConciergeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/study-nook/': {
      id: '/_app/study-nook/'
      path: '/study-nook'
      fullPath: '/study-nook/'
      preLoaderRoute: typeof AppStudyNookIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lobby/': {
      id: '/_app/lobby/'
      path: '/lobby'
      fullPath: '/lobby/'
      preLoaderRoute: typeof AppLobbyIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/guide/': {
      id: '/_app/guide/'
      path: '/guide'
      fullPath: '/guide/'
      preLoaderRoute: typeof AppGuideIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/study-nook/$zoneId': {
      id: '/_app/study-nook/$zoneId'
      path: '/study-nook/$zoneId'
      fullPath: '/study-nook/$zoneId'
      preLoaderRoute: typeof AppStudyNookZoneIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lobby/$threadId': {
      id: '/_app/lobby/$threadId'
      path: '/lobby/$threadId'
      fullPath: '/lobby/$threadId'
      preLoaderRoute: typeof AppLobbyThreadIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/guide/$estId': {
      id: '/_app/guide/$estId'
      path: '/guide/$estId'
      fullPath: '/guide/$estId'
      preLoaderRoute: typeof AppGuideEstIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/logs': {
      id: '/_app/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/establishments': {
      id: '/_app/admin/establishments'
      path: '/admin/establishments'
      fullPath: '/admin/establishments'
      preLoaderRoute: typeof AppAdminEstablishmentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppConciergeRoute: typeof AppConciergeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppModerationRoute: typeof AppModerationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminEstablishmentsRoute: typeof AppAdminEstablishmentsRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppGuideEstIdRoute: typeof AppGuideEstIdRoute
  AppLobbyThreadIdRoute: typeof AppLobbyThreadIdRoute
  AppStudyNookZoneIdRoute: typeof AppStudyNookZoneIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppGuideIndexRoute: typeof AppGuideIndexRoute
  AppLobbyIndexRoute: typeof AppLobbyIndexRoute
  AppStudyNookIndexRoute: typeof AppStudyNookIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConciergeRoute: AppConciergeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppModerationRoute: AppModerationRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminEstablishmentsRoute: AppAdminEstablishmentsRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppGuideEstIdRoute: AppGuideEstIdRoute,
  AppLobbyThreadIdRoute: AppLobbyThreadIdRoute,
  AppStudyNookZoneIdRoute: AppStudyNookZoneIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppGuideIndexRoute: AppGuideIndexRoute,
  AppLobbyIndexRoute: AppLobbyIndexRoute,
  AppStudyNookIndexRoute: AppStudyNookIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
